name: todo_app_vh
description: Basic To Do App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  api:
    path: "packages/api"
  local_storage_api:
    path: "packages/local_storage_api"
  todos_repository:
    path: "packages/todos_repository"
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  just_audio: ^0.9.34

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
